// Please note that this visualization is ENTIRELY AI generated by Gemini 3.1 Pro,
// We do not view it as part of the actual material we are submitting,
// Instead, it is a useful tool for making sense of the results of our modeling.

// Setup for importing the external Vis.js network library
function loadSources() {
  if (!document.getElementById('visjs-network-script')) {
    var visImport = document.createElement('script');
    visImport.setAttribute('id', 'visjs-network-script');
    visImport.setAttribute('src', 'https://unpkg.com/vis-network/standalone/umd/vis-network.min.js');
    visImport.setAttribute('crossorigin', 'anonymous');
    document.head.appendChild(visImport);
  }
}

function loadCourseGraph() {
  if (typeof vis === 'undefined') {
    setTimeout(loadCourseGraph, 100);
    return;
  }

  // --- 1. DATA EXTRACTION HELPERS ---
  function getTuples(rel) {
    try { return eval(rel).tuples(); } catch (e) { return []; }
  }

  let roles = {};       // Primary role for labeling
  let levels = {};      // Vertical tier (0 = Top, 4 = Bottom)
  let categories = {};  // Broad category for node coloring
  let extraTags = {};   // Notes for pathway fulfillment 

  // --- 2. DEFINE THE 5 TIERS (LEVELS) ---
  
  // Helper to assign primary degree requirements to specific tiers
  function assignPrimary(rel, roleStr, cat, level) {
    getTuples(rel).forEach(t => {
      let cId = t.atoms()[1].toString(); 
      roles[cId] = roleStr;
      categories[cId] = cat;
      levels[cId] = level;
    });
  }

  // Tier 0: Intros
  assignPrimary('intro1', 'Intro 1', 'Intro', 0);
  assignPrimary('intro2', 'Intro 2', 'Intro', 0);
  
  // Tier 1: Intermediates
  assignPrimary('inter1', 'Inter 1', 'Intermediate', 1);
  assignPrimary('inter2', 'Inter 2', 'Intermediate', 1);
  assignPrimary('inter3', 'Inter 3', 'Intermediate', 1);
  assignPrimary('inter4', 'Inter 4', 'Intermediate', 1);
  assignPrimary('inter5', 'Inter 5', 'Intermediate', 1);
  
  // Tier 3: Upper Level (Tier 2 is reserved for Pathway Cores below)
  assignPrimary('upperLevel', 'Additional Upper Level', 'UpperLevel', 3);
  
  // Tier 4: Electives
  assignPrimary('elec1', 'Elective 1', 'Elective', 4);
  assignPrimary('elec2', 'Elective 2', 'Elective', 4);
  assignPrimary('elec3', 'Elective 3', 'Elective', 4);

  // --- 3. PROCESS PATHWAYS & CROSS-REFERENCE INTERMEDIATES ---
  let pathwayNames = {};
  getTuples('name').forEach(t => {
    let reqId = t.atoms()[0].toString();
    // Strip Forge numerical suffixes (e.g., "AiMlP0" -> "AiMl")
    pathwayNames[reqId] = t.atoms()[1].toString().replace(/P\d*$/, ''); 
  });

  function processPathwayReq(rel, typeStr, isCore) {
    getTuples(rel).forEach(t => {
      let reqId = t.atoms()[0].toString();
      let cId = t.atoms()[1].toString();
      let pName = pathwayNames[reqId] || "Pathway";
      
      if (isCore) {
        // Tier 2: Pathway Core / Related
        roles[cId] = `${pName} Pathway\n[${typeStr}]`;
        categories[cId] = 'Pathway';
        levels[cId] = 2; 
      } else {
        // Add notes to Intermediates (Tier 1) about which pathway they fulfill
        if (!extraTags[cId]) extraTags[cId] = [];
        extraTags[cId].push(`Fulfills: ${pName} [${typeStr}]`);
      }
    });
  }

  processPathwayReq('core1', 'Core 1', true);
  processPathwayReq('coreOrRelated', 'Core/Related', true);
  processPathwayReq('intermediate1', 'Inter 1', false);
  processPathwayReq('intermediate2', 'Inter 2', false);
  processPathwayReq('intermediate3', 'Inter 3', false);

  // --- 4. EXTRACT METADATA ---
  let courseDepts = {};
  getTuples('dept').forEach(t => { courseDepts[t.atoms()[0].toString()] = t.atoms()[1].toString(); });
  
  let upperDivSet = new Set();
  getTuples('upperDiv').forEach(t => { upperDivSet.add(t.atoms()[0].toString()); });

  let interTypes = {};
  getTuples('intermediateType').forEach(t => { 
    // Strip suffixes (e.g., "FoundationsI0" -> "Foundations")
    interTypes[t.atoms()[0].toString()] = t.atoms()[1].toString().replace(/I\d*$/, ''); 
  });

  // --- 5. BUILD VISUALIZATION NODES ---
  let nodes = new vis.DataSet([]);
  const courses = typeof Course !== 'undefined' ? Course.atoms(true) : [];
  
  const categoryColors = {
    'Intro': '#fffacd',        // Light Yellow
    'Intermediate': '#add8e6', // Light Blue
    'Pathway': '#90ee90',      // Light Green
    'UpperLevel': '#ffb6c1',   // Light Pink
    'Elective': '#e6e6fa'      // Light Purple
  };

  courses.forEach(c => {
    let id = c.toString();
    let lvl = levels[id] !== undefined ? levels[id] : 5; 
    let role = roles[id] || "Unassigned";
    let cat = categories[id] || 'Elective';
    let isUpper = upperDivSet.has(id);
    
    // Build the label line by line
    let labelParts = [`*${role}*`]; 
    labelParts.push(`${id} (${courseDepts[id] || "Dept"})`);
    
    if (interTypes[id]) {
      labelParts.push(`Type: ${interTypes[id]}`);
    }
    if (extraTags[id]) {
      labelParts.push(extraTags[id].join('\n')); // Add pathway fulfillment notes
    }
    if (isUpper) {
      labelParts.push("⬆ Upper Div");
    }

    nodes.add({
      id: id,
      label: labelParts.join('\n'),
      level: lvl, // Strict explicit vertical ordering
      shape: 'box',
      color: { 
          background: categoryColors[cat] || '#f4f4f4', 
          border: isUpper ? '#333333' : '#999999' 
      },
      borderWidth: isUpper ? 3 : 1,
      font: { multi: 'md', face: 'monospace', align: 'center' }
    });
  });

  // --- 6. BUILD VISUALIZATION EDGES ---
  let edges = new vis.DataSet([]);
  getTuples('prereq').forEach(t => {
    edges.add({
      from: t.atoms()[0].toString(),
      to: t.atoms()[1].toString(),
      arrows: 'to',
      color: '#888888',
      width: 2
    });
  });

  // --- 7. RENDER GRAPH ---
  var container = document.createElement('div');
  container.setAttribute('id', 'course-network');
  // Expanded width/height to accommodate the strict 5-tier horizontal spread
  container.setAttribute('style', 'width: 100%; height: 800px; border: 1px solid lightgray; margin-top: 10px; border-radius: 8px; background-color: #ffffff;');
  div.appendChild(container);

  var data = { nodes: nodes, edges: edges };
  var options = {
    layout: {
      hierarchical: { 
        direction: "UD", 
        levelSeparation: 150, 
        nodeSpacing: 180, 
        treeSpacing: 200 
      }
    },
    physics: false
  };
  
  new vis.Network(container, data, options);
}

// Initialization block
div.innerHTML = '';
div.style.overflow = 'hidden'; 
if (!document.getElementById('visjs-network-script')) {
  var alertMsg = document.createElement('p');
  alertMsg.innerText = 'Click "Execute" again if the graph does not immediately render.';
  alertMsg.style.color = '#d9534f';
  div.appendChild(alertMsg);
}

loadSources();
loadCourseGraph();